// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adxnbdxlaonqftbocjqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeG5iZHhsYW9ucWZ0Ym9janFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMjE3ODYsImV4cCI6MjA4NDY5Nzc4Nn0.GhhOWq0Imp9i0DVk5e6UTdRGMKMI4tyqkUvZwzf8CFw";

// Some embedded contexts (or strict privacy settings) can throw on localStorage access.
// If that happens, Supabase auth init can hang and keep admin pages on an infinite spinner.
// This safe storage wrapper prevents that.
const safeStorage: Storage = (() => {
  try {
    if (typeof window !== "undefined" && window.localStorage) {
      const testKey = "__sb_storage_test__";
      window.localStorage.setItem(testKey, testKey);
      window.localStorage.removeItem(testKey);
      return window.localStorage;
    }
  } catch {
    // fall through to in-memory storage
  }

  const mem: Record<string, string> = {};
  return {
    getItem: (key: string) => (key in mem ? mem[key] : null),
    setItem: (key: string, value: string) => {
      mem[key] = value;
    },
    removeItem: (key: string) => {
      delete mem[key];
    },
    clear: () => {
      for (const k of Object.keys(mem)) delete mem[k];
    },
    key: (index: number) => Object.keys(mem)[index] ?? null,
    get length() {
      return Object.keys(mem).length;
    },
  } as Storage;
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});